export const PATH = {
    USER_LOGIN: "/login",
    USER_REGISTER: "/register",
    USER_LOGOUT: "/logout",
    USERS_ROUTE:'/users',
    USER_ID_ROUTE:'/user/:id',
    EDIT_USER_ROUTE:'/user/edit/:id',
    ACTIVATE_USER_ROUTE:'/user/activate/:id',  
    USER_PROFILE_ROUTE:'/user/profile/:id', 
    BRANCHES_ROUTE:'/branches',
    BRANCH_ID_ROUTE:'/branch/:id',  
    EDIT_BRANCH_ROUTE:'/branch/edit/:id',
    DEPARTMENTS_ROUTES:'/departments',
    DEPARTMENT_ID_ROUTE:'/department/:id',
    EDIT_DEPARTMENT_ROUTE:'/department/edit/:id',
    DEVICES_ROUTES:'/devices',  
    DEVICE_ID_ROUTE:'/device/:id',
    EDIT_DEVICE_ROUTE:'/device/edit/:id',
    POSITIONS_ROUTES:'/positions',  
    POSITION_ID_ROUTE:'/position/:id',
    EDIT_POSITION_ROUTE:'/position/edit/:id',
}